//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photography
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLING
    {
        public int BillingId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public int CardId { get; set; }
        public string State { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public int Zip { get; set; }
    
        public virtual CREDIT_CARD CREDIT_CARD { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual VENDOR VENDOR { get; set; }
    }
}
