//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photography
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART
    {
        public CART()
        {
            this.INVOICEs = new HashSet<INVOICE>();
        }
    
        public int CartId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public byte[] IsActive { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual VENDOR VENDOR { get; set; }
        public virtual ICollection<INVOICE> INVOICEs { get; set; }
    }
}
