//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photography
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREDIT_CARD
    {
        public CREDIT_CARD()
        {
            this.BILLINGs = new HashSet<BILLING>();
            this.CUSTOMERs = new HashSet<CUSTOMER>();
        }
    
        public int CardId { get; set; }
        public int CustomerId { get; set; }
        public string CardType { get; set; }
        public string CardNumber { get; set; }
        public string NameOnCard { get; set; }
        public string ExpirationDate { get; set; }
        public int SecurityCode { get; set; }
        public string Salt { get; set; }
    
        public virtual ICollection<BILLING> BILLINGs { get; set; }
        public virtual ICollection<CUSTOMER> CUSTOMERs { get; set; }
    }
}
