//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photography
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREDIT_CARD
    {
        public CREDIT_CARD()
        {
            this.BILLINGs = new HashSet<BILLING>();
        }
    
        public int CardId { get; set; }
        public string CardType { get; set; }
        public long CardNumber { get; set; }
        public string NameOnCard { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int SecurityCode { get; set; }
    
        public virtual ICollection<BILLING> BILLINGs { get; set; }
    }
}
