//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photography
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY
    {
        public INVENTORY()
        {
            this.PHOTOS = new HashSet<Photo>();
        }
    
        public int InventoryId { get; set; }
        public decimal RetailPrice { get; set; }
        public decimal WholeSalePrice { get; set; }
        public int NumInStock { get; set; }
    
        public virtual ICollection<Photo> PHOTOS { get; set; }
    }
}
