//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photography
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHOTO_CART
    {
        public int PhotoId { get; set; }
        public int CartId { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual CART CART { get; set; }
        public virtual Photo Photo { get; set; }
    }
}
